### ISSUE TITLE
Scale option always set to 1

### ISSUE THREAD

**Issue by Ixolite** [patrikroy/FileToVox-LazyGUI#2]
Hi,

It seems that the scale option is always set to 1 for me in the command line, no matter what value is entered in the GUI.

![image](https://user-images.githubusercontent.com/66519660/83944747-20b19300-a806-11ea-9ef9-69e254dbdc17.png)

**Comment by patrikroy** [comment]
My bad, the scale parameter has changed (`--sc` instead of `--s`).
I'll release a hotfix as soon as I can. Watch for version 1.3b
